// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcxgbTaYgk6uT7ZAJyAAx_JjFanWvTDVs',
    appId: '1:1097697803791:web:42d70307d5eb0c7bfaad7a',
    messagingSenderId: '1097697803791',
    projectId: 'anestezi',
    authDomain: 'anestezi.firebaseapp.com',
    storageBucket: 'anestezi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfc5onYy08uG-w50SHDxpyHZqDdOL8Bzw',
    appId: '1:1097697803791:android:f9197a504064a85afaad7a',
    messagingSenderId: '1097697803791',
    projectId: 'anestezi',
    storageBucket: 'anestezi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCJx22wWQpMUzfoYHC7yPVeFRYLbvFiQ',
    appId: '1:1097697803791:ios:877cea48a29d8caffaad7a',
    messagingSenderId: '1097697803791',
    projectId: 'anestezi',
    storageBucket: 'anestezi.firebasestorage.app',
    iosBundleId: 'com.example.anestezi',
  );
}
