import 'package:flutter/material.dart';

class RespiratoryPhysiologyAnesthesiaItem {
  final String title;
  final String description;
  final String? subtitle;
  final String? additionalInfo;

  RespiratoryPhysiologyAnesthesiaItem({
    required this.title,
    required this.description,
    this.subtitle,
    this.additionalInfo,
  });
}

class RespiratoryPhysiologyAnesthesiaCategory {
  final String categoryName;
  final List<RespiratoryPhysiologyAnesthesiaItem> items;

  RespiratoryPhysiologyAnesthesiaCategory({
    required this.categoryName,
    required this.items,
  });
}

class RespiratoryPhysiologyAnesthesiaData {
  static List<RespiratoryPhysiologyAnesthesiaCategory> getRespiratoryPhysiologyAnesthesiaData(BuildContext context) {
    return [
      RespiratoryPhysiologyAnesthesiaCategory(
        categoryName: 'Functional Respiratory Anatomy',
        items: [
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Thoracic Cage & Respiratory Muscles',
            description: 'Diaphragm → responsible for ~75% of chest volume change',
            subtitle: 'Normal breathing: diaphragm + intercostals (inspiration). Expiration is passive',
            additionalInfo: 'Forced inspiration: SCM, scalene, pectorals\nForced/standing expiration: abdominal + intercostals\nPharyngeal muscles: maintain airway patency (sleep/apnea relevance)',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Tracheobronchial Tree - Trachea',
            description: '10–13 cm (cricoid lower margin → carina)',
            subtitle: 'Diameter: male (2.3 × 1.8 cm, narrowest 1.7), female (2.0 × 1.4 cm, narrowest 1.3)',
            additionalInfo: 'Carina at sternal angle',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Right Bronchus',
            description: 'Upper lobe branch after 2 cm (male), 1.5 cm (female)',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Left Bronchus',
            description: 'Upper/lower lobe branch after 5 cm (male), 4.5 cm (female)',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Branching',
            description: 'Total 23 generations of branching. Gas exchange at 17–19th gen respiratory bronchioles',
            subtitle: 'Small airways → dependent on radial traction\nLarge airways → dependent on total lung volume',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Alveoli',
            description: 'Diameter: 0.05–0.33 mm',
            subtitle: 'Type I pneumocytes → gas exchange (~90% surface)',
            additionalInfo: 'Type II pneumocytes → surfactant production, capable of division & Type I transformation',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Pulmonary Circulation & Lymphatics',
            description: 'Pulmonary circulation → metabolic supply up to bronchioles',
            subtitle: 'Bronchial circulation → bronchial walls + terminal bronchioles',
            additionalInfo: 'Pulmonary capillaries ≈ 10 µm (single RBC)\nPulmonary lymphatic flow ≈ 20 mL/hr',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Innervation',
            description: 'Diaphragm: C3–C5 (phrenic nerve)',
            subtitle: 'Injury above C5 → no spontaneous breathing',
            additionalInfo: 'Vagus → sensory + parasympathetic (M receptor, bronchoconstriction)\nSympathetic T1–T4 → bronchodilation\nPulmonary vessels: α1 (VC), β2 (VD), parasympathetic NO-mediated VD',
          ),
        ],
      ),
      RespiratoryPhysiologyAnesthesiaCategory(
        categoryName: 'Mechanics of Breathing',
        items: [
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Spontaneous',
            description: 'End-expiration intrapleural pressure: –5 cmH₂O',
            subtitle: 'Inspiration → intrapleural: –9 cmH₂O, alveolar: –3/–4 cmH₂O',
            additionalInfo: 'Transpulmonary = Palv – Pplev',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Mechanical Ventilation',
            description: 'VT generated by positive pressure',
            subtitle: 'Expiration → passive when pressure is removed',
          ),
        ],
      ),
      RespiratoryPhysiologyAnesthesiaCategory(
        categoryName: 'Lung Mechanics',
        items: [
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Compliance',
            description: 'CL (lung) = 150–100 mL/cmH₂O',
            subtitle: 'CW (chest wall) = 200 mL/cmH₂O',
            additionalInfo: 'Ctotal ≈ 100 mL/cmH₂O',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Surface Tension',
            description: 'Laplace: P = 2T / r',
            subtitle: 'Surfactant reduces surface tension → prevents collapse of small alveoli',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Lung Volumes - FRC',
            description: 'FRC → residual volume after normal expiration',
            subtitle: 'Obesity & GA → reduce FRC',
            additionalInfo: 'FRC ↓ by 0.8–1 L supine, ↓ 0.4–0.5 L after GA induction\nClosing capacity ↑ with age: exceeds FRC at 44 supine, 66 upright',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Airway Resistance',
            description: 'Normal: 0.5–2 cmH₂O/L/s',
            subtitle: 'Greatest resistance: medium bronchi',
            additionalInfo: 'Laminar flow: Re <1000; turbulent: Re >1500\nForced expiration → dynamic airway collapse (pursed-lip breathing)',
          ),
        ],
      ),
      RespiratoryPhysiologyAnesthesiaCategory(
        categoryName: 'Ventilation–Perfusion',
        items: [
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Normal V/Q',
            description: 'Normal VA = 4 L/min, Q = 5 L/min → V/Q = 0.8',
            subtitle: 'Dead space: 2 mL/kg (~150 mL)',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'West Zones',
            description: 'Zone 1: PA > Pa > Pv (↑ in ventilation)',
            subtitle: 'Zone 2: Pa > PA > Pv',
            additionalInfo: 'Zone 3: Pa > Pv > PA (best perfusion)\nZone 4: interstitial edema/atelectasis',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Hypoxic Pulmonary Vasoconstriction',
            description: 'Response to alveolar hypoxia',
            subtitle: 'Volatile agents inhibit HPV',
          ),
        ],
      ),
      RespiratoryPhysiologyAnesthesiaCategory(
        categoryName: 'Gas Pressures',
        items: [
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'PAO₂',
            description: 'Room air, sea level ≈ 100 mmHg',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'PaO₂',
            description: 'Normal = 60–100 mmHg',
            subtitle: 'PaO₂ ≈ 120 – (age/3)',
            additionalInfo: 'A–a gradient: <15 mmHg (↑ with age)',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'PvO₂',
            description: '≈ 40 mmHg',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'PaCO₂',
            description: 'Normal = 40 ± 4 mmHg',
            subtitle: 'EtCO₂ ≈ PaCO₂ – 5 mmHg',
          ),
        ],
      ),
      RespiratoryPhysiologyAnesthesiaCategory(
        categoryName: 'Oxygen Transport',
        items: [
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Hb O₂ Carrying Capacity',
            description: '1 g Hb carries 1.39 mL O₂',
            subtitle: 'Normal Hb saturation ≈ 97% → CaO₂ ≈ 19.5 mL/dL',
            additionalInfo: 'O₂ extraction fraction ≈ 25%',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'O₂ Store',
            description: 'Within FRC ≈ 1500 mL',
            subtitle: '100% O₂ preoxygenation → 4–5 min apnea time',
          ),
        ],
      ),
      RespiratoryPhysiologyAnesthesiaCategory(
        categoryName: 'Carbon Dioxide Transport',
        items: [
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'CO₂ Forms',
            description: 'Dissolved + bicarbonate (main) + carbamino',
            subtitle: 'Haldane effect → deoxygenated Hb increases CO₂ carrying capacity',
            additionalInfo: 'Normal VCO₂ ≈ 200 mL/min',
          ),
        ],
      ),
      RespiratoryPhysiologyAnesthesiaCategory(
        categoryName: 'Respiratory Control',
        items: [
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Medulla',
            description: 'Dorsal group → inspiration',
            subtitle: 'Ventral group → expiration',
            additionalInfo: 'Pontine centers → modulate breathing pattern',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Central Chemoreceptors',
            description: 'CSF pH/PCO₂',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Peripheral Chemoreceptors',
            description: 'PaO₂ <50 mmHg',
            subtitle: 'Carotid body most sensitive to PaO₂',
          ),
        ],
      ),
      RespiratoryPhysiologyAnesthesiaCategory(
        categoryName: 'Effects of Anesthesia',
        items: [
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'FRC & Closing Capacity',
            description: '↓ FRC, ↓ closing capacity → ↑ shunt risk',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Volatile Agents',
            description: 'Bronchodilation, inhibit HPV',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'High FiO₂',
            description: 'Absorption atelectasis',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Opioid + N₂O',
            description: 'Slow, deep breathing',
          ),
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'Volatile Agents',
            description: 'Rapid, shallow breathing',
          ),
        ],
      ),
      RespiratoryPhysiologyAnesthesiaCategory(
        categoryName: 'Key Exam Spots',
        items: [
          RespiratoryPhysiologyAnesthesiaItem(
            title: 'SUMMARY SPOT QUESTIONS',
            description: 'Diaphragm: C3–C5, responsible for ~75% chest volume change',
            subtitle: 'FRC ↓ by 0.8–1 L supine, ↓ 0.4–0.5 L after GA',
            additionalInfo: 'Normal V/Q = 0.8, Dead space: 2 mL/kg\nPaO₂ ≈ 120 – (age/3)\n1 g Hb carries 1.39 mL O₂\n100% O₂ preoxygenation → 4–5 min apnea time',
          ),
        ],
      ),
    ];
  }
}
